version: "3"
services:
  app:
    image: { { cookiecutter.project_name } }
    build: .
    volumes:
      - .:/app

  jupyter:
    depends_on:
      - app
    image: { { cookiecutter.project_name } }
    ports:
      - "8080:8080"
    command:
      [
        "pipenv",
        "run",
        "jupyter",
        "lab",
        "--ip=0.0.0.0",
        "--port=8080",
        "--allow-root",
      ]
